# Generated by Django 2.1.2 on 2018-10-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id_est', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_est', models.CharField(max_length=20)),
                ('correo_est', models.CharField(max_length=20)),
                ('usuario_est', models.CharField(max_length=20)),
                ('password_est', models.CharField(max_length=20)),
            ],
        ),
    ]
