# Generated by Django 2.1.2 on 2018-10-10 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_auto_20181009_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='usuario_est',
        ),
    ]
